### ISSUE TITLE
Unable to complete Module 4  Notebook 1.0 (Running experiments in Azure ML)

### ISSUE THREAD

**Issue by sthoward0914** [MicrosoftLearning/dp-090-databricks-ml#58]
# Module: 04
#### Step: Set MLflow tracking URL

First of all, I am currently running running 10.0 ML cluster (Confirmed it is ML). I have tried several versions since the previous issue was closed, and all of them run into issues if I do not add in cells for pip install. This is true of this notebook as well, even using 10.0 ML.

With that in mind, I added cells to run these pip installs to get me past the first few cells:
%pip install azureml 
%pip install sklearn_pandas
%pip install azureml.core
%pip install mlflow
%pip install azureml.mlflow

Simply stated, across several versions including both ML and non ML cluster versions, I get errors on the subsequent steps. Only when I do the pip installs am I able to successfully execute the cells in the notebook.

I have not gone back to the previous notebooks to see if I can execute them on ML versions of the clusters without the pip installs, but since some of the pip installs here are the same as previous notebooks, I suspect it is the case even with ML clusters.

(Note: I did not try re-creating the cluster and removing %pip install mlflow to see if azureml.mlflow was adequate. That probably should be tested. I'm just running out of time on it.)

**Comment by GraemeMalcolm** [comment]
@sthoward0914 , can you confirm @madiepev 's question above? Had you followed the instructions to install the libraries?

**Comment by sthoward0914** [comment]
I went through the setup steps, but honestly speaking, I may have missed something. I didn't retry. You can close this. I'll try the setup steps again this weekend, and if I have problems, I'll bring it back up. Otherwise, I'll just figure it was my screw-up.

Thank you.

**Comment by GraemeMalcolm** [comment]
Fair enough!
