### ISSUE TITLE
Issue in deployment | 2.0 Deploying Models in Azure Machine Learning

### ISSUE THREAD

**Issue by test4293** [MicrosoftLearning/dp-090-databricks-ml#62]
# Module: 4
#### Step: 00

Description of issue : Deployment failed. When i check the deployment logs of I found this "ERROR: Could not find a version that satisfies the requirement sanic~=21.6.0 (from azureml-inference-server-http~=0.4.1->azureml-defaults->-r /azureml-environment-setup/condaenv. "

Repro steps:

1. You can run : "2.0 Deploying Models in Azure Machine Learning
[build.log](https://github.com/MicrosoftLearning/dp-090-databricks-ml/files/8101884/build.log)
"
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by madiepev** [comment]
@test4293 and @MOC-Labs-Review I couldn't reproduce this error. Is it only when deploying the registered model that you see this error? No error occurs before?

**Comment by test4293** [comment]
> @test4293 and @MOC-Labs-Review I couldn't reproduce this error. Is it only when deploying the registered model that you see this error? No error occurs before?

Yes, i only see this error while deploying the model
