### ISSUE TITLE
Lab 4b - cannot create Container Registry

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/dp-090-databricks-ml#68]
# Module: 04
#### Step: cmd 27

Description of issue
The deployment of the ACI fails due to restrictions put in place by the cloud slice governance. The service cannot create a container registry in order to deploy service (see error in image) which has to be based on the subscription permissions. 

![image](https://user-images.githubusercontent.com/46732841/168185351-da2f7a63-4091-45b2-a5b9-932a733ececc.png)

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
This course was not designed for Cloud Slice (Azure Pass was specified). If you're using cloud sure then the hoster will need to adapt the policies to remove constraints. This is not a content bug.
