### ISSUE TITLE
Instructions on the very first step lead students to work outside of the lab VM

### ISSUE THREAD

**Issue by ClementinoDeMendonca-msft** [MicrosoftLearning/dp-090-databricks-ml#69]
# Module: 00 - all modules
#### Step: 01

**Description of issue**

Instructions on the very first step lead students to work outside of the lab VM.

**Recommended solution:**

Instead of:

> 1) In the Azure portal 'https://portal.azure.com', create a new Azure Databricks resource, specifying the following settings:

it should say:

> _1) Open a browser window in the virtual machine._ 
> 2) In the Azure portal 'https://portal.azure.com', create a new Azure Databricks resource, specifying the following settings:

Plus the "https://portal.azure.com" link should be made into a T (Type text) markup so students don't have to copy and paste it into the VM.

**Repro steps:**
No repro steps.

**Comment by GraemeMalcolm** [comment]
No, the instructions should work in multiple modalities - including a BYO environment with no VM
