### ISSUE TITLE
Module 1 - Getting Started with Azure Databricks

### ISSUE THREAD

**Issue by annav88** [MicrosoftLearning/dp-090-databricks-ml#73]
# Module: 01
#### Step: 02 

Description of issue

I had 5 students today (Cloudslice) not having the RBAC on the Azure Databricks resource. It would be nice if we could add an instruction (with Optional flag) for those who get that error message, to go to portal.azure.com and assign the Owner RBAC to the Dbricks resource for the Cloudslice login.

Repro steps:

1. Please see the attached image displaying the error students faced
![Uploading dbricks.png…]()

**Comment by annav88** [comment]
![dbricks](https://user-images.githubusercontent.com/83666021/188129010-465cd3d7-f34d-4005-a964-19e4c9f1e250.png)
screenshot (not sure if previous one was actually properly uploaded)

**Comment by GraemeMalcolm** [comment]
@madiepev There's an issue in the cloudslice that the learner's account is not added to the Owner role for the Databricks resource (instead, they're added to a custom LODSOwner role). We need to either have the learner explicitly add themselves to the role after provisioning Databricks, or change the lab to use a script to provision and assign the RBAC membership as we're doing in the https://GitHub.com/MicrosoftLearning/mslearn-databricks labs.

**Comment by GraemeMalcolm** [comment]
(you may need to work with Skillable to adjust the Azure policies to accommodate this)
