### ISSUE TITLE
Module 4, Lab 4B, Notebook 2.0: ACI creation blocked by policy

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/dp-090-databricks-ml#75]
# Module: 04
#### Step: cmd 27

 "code": "AciDeploymentFailed",
  "statusCode": 400,
  "message": "Error while trying to create an ACR for the workspace. Please use a different workspace that has an ACR associated with it or 
                                                                disable the policies that intervene with resource creation on your behalf. Instructions on workspace creation can be found here: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-manage-workspace 
                                                                Please see error for details: Service invocation failed!
Request: GET cert-southcentralus.experiments.azureml.net/rp/workspaces/subscriptions/f63d7687-8474-4abd-9b8e-e4ad7f8bdc61/providers/Microsoft.MachineLearningServices/locations/southcentralus/workspaceOperationsStatus/82ccc1bb-415d-4cae-bfc5-695501124ac9
Status Code: 400 BadRequest
Error Code: ValidationError
Reason Phrase: Bad Request",
  "details": []
}

WebserviceException: WebserviceException:
	Message: Service deployment polling reached non-successful terminal state, current service state: Unhealthy
Operation ID: 779ea5cb-455f-4b63-9f18-29b03eea55d8
Current sub-operation type not known, more logs unavailable.
Error:
{
  "code": "AciDeploymentFailed",
  "statusCode": 400,
  "message": "Error while trying to create an ACR for the workspace. Please use a different workspace that has an ACR associated with it or 
                                                                disable the policies that intervene with resource creation on your behalf. 
Repro steps:

1. Tried to manually create an ACI instance in the portal, disallowed by policy
1.{"code":"InvalidTemplateDeployment","message":"The template deployment failed because of policy violation. Please see details for more information.","details":[{"code":"RequestDisallowedByPolicy","target":"nyc-taxi-service","message":"Resource 'nyc-taxi-service' was disallowed by policy dp-090_ACP_v2

**Comment by ZekeStarr** [comment]
It looks like you were running this lab on our (Skillable's) platform (judging from the Policy name).

Each lab is tailored to the Module that it is named after, so resources that can be deployed in one Module/Lab cannot necessarily be deployed in another. We've tested the lab for Module 04's labs and confirmed that the ACI/R deployment is successful, both in the notebook and manually.

I would recommend you launch the labs for Module 04 directly and see if you are still experiencing the issue.
