### ISSUE TITLE
Error Lab - Notebook: Using MLFlow to Track Experiments

### ISSUE THREAD

**Issue by AdolfoG22** [MicrosoftLearning/dp-090-databricks-ml#76]
Module 3

Lab - Notebook: 01 - Using MLflow to Track Experiments

Databricks environment: Runtime version: ML 12.0
Section: view the experiments
Code: client.list_experiments()
AttributeError: 'MlflowClient' object has no attribute 'list_experiments'
Comment: Possibly deprecated in version 2.0 of MLFlow

I attach details of the execution
[01 - Using MLflow to Track Experiments - Databricks.pdf](https://github.com/MicrosoftLearning/dp-090-databricks-ml/files/10290823/01.-.Using.MLflow.to.Track.Experiments.-.Databricks.pdf)

**Comment by socullen** [comment]
I faced the same issue. Could you please provide a workaround?

**Comment by iamramengirl** [comment]
Based the following documentation, **MLflow 2.0 advisory: In legacy versions of MLflow (<2.0) use method list_experiments instead.**

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-track-experiments-mlflow#getting-all-the-experiments

I will create a pull request to propose the following change for later MLflow versions.

**(1) To list experiments**

`client.list_experiments()`

should be changed to

```
experiments = client.search_experiments()
for exp in experiments:
    print(exp.name)
```

**(2) To assign the experiment_id**

`experiment_id = client.list_experiments()[experiment_num].experiment_id`

should be changed to

`experiment_id = client.search_experiments()[experiment_num].experiment_id`

**Comment by madiepev** [comment]
Issue has been fixed. Thanks for reporting it.
