### ISSUE TITLE
Lab 4 - AML resource creation issue

### ISSUE THREAD

**Issue by elenamoor** [MicrosoftLearning/dp-090-databricks-ml#77]
# Module: 4
#### Step: 2 - create the AML resource

Description of issue

Students cannot create a resource even when every requirement from the instructions are met. 

Repro steps:

1. Try to create an aml resource
2. it will not pass the validation giving the error saying "resource <resource details> was disallowed by policy. Policy: dp-090_acp_v3
3. within the policy I see the Deny action assigned to all correct AML specifications. See attachments.
![dp-090 bug](https://user-images.githubusercontent.com/15022465/209246642-21a5d077-e2a1-481b-9da4-96061653d613.png)

**Comment by madiepev** [comment]
@elenamoor thanks for reporting this. I've raised the issue with the team responsible and will get back to you as soon as possible.

**Comment by madiepev** [comment]
This issue is resolved
