### ISSUE TITLE
Issue with fmin() function

### ISSUE THREAD

**Issue by socullen** [MicrosoftLearning/dp-090-databricks-ml#80]
# Module: Optional exercise
#### Step: Select a search algorithm

Description of issue
When performing the fmin() function the following error is shown.
<img width="761" alt="image" src="https://user-images.githubusercontent.com/85845774/213451297-16a0c994-c70c-4793-9117-af3a31708c0f.png">

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
Issue has been fixed. Thanks for reporting this!
