### ISSUE TITLE
Request to update the Azure Databricks Module

### ISSUE THREAD

**Issue by iamramengirl** [MicrosoftLearning/dp-090-databricks-ml#81]
# Module: 

1. https://learn.microsoft.com/en-us/training/modules/track-azure-databricks-experiments-azure-machine-learning/?ns-enrollment-type=learningpath&ns-enrollment-id=learn.wwl.build-operate-machine-learning-solutions-azure-databricks
2. https://learn.microsoft.com/en-us/training/modules/deploy-azure-databricks-models-azure-machine-learning/?ns-enrollment-type=learningpath&ns-enrollment-id=learn.wwl.build-operate-machine-learning-solutions-azure-databricks

#### Step: 00

The above 2 modules discuss information about Azure Machine Learning version 1.0, which is already deprecated. Azure ML CLI/SDK version 2.0 is now available. Request to update the modules as well as the exercises (Notebook). Thank you!

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
We're working on creating content for v2 in parallel, which will be released soon. This content will still exist for those interested in v1 content as it is not deprecated yet. Thank you for flagging this.
