### ISSUE TITLE
Notebook import fails

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/dp-090-databricks-ml#82]
All modules affected-

Importing the notebook URL fails with an error message of "Unexpected end of JSON input"

However, downloading the file and uploading it renders no error message.

![image](https://user-images.githubusercontent.com/72228536/223186812-ffde23cb-107a-445f-b3d3-3d881154d29c.png)

**Comment by GraemeMalcolm** [comment]
Thanks @IamUser1337 for reporting. Instructions updated to download locally and then import.
