### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by IamUser1337** [MicrosoftLearning/dp-090-databricks-ml#83]
Multiple Modules -

Error Message, " no module named sklearn_pandas"
Error Message "no module named azureml"
Error Message "no module named azureml.corel"

![image](https://user-images.githubusercontent.com/72228536/223187575-329fd4f1-3609-43b0-9f5d-507e7db3b356.png)
![image](https://user-images.githubusercontent.com/72228536/223188015-ac5c2928-2b18-4835-a9f4-567b4b36596f.png)
![image](https://user-images.githubusercontent.com/72228536/223188402-728c212f-7544-4d70-8790-4844af4a2299.png)

**Comment by douwevandenberg** [comment]
You need to install some modules to your cluster in an earlier step. This should fix your problem.
