### ISSUE TITLE
Create table UI changed

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/dp-090-databricks-ml#84]
# Module: 01
#### Step: All

Description of issue
The steps to create a table in the Azure Databricks UI are outdated. The biggest issue: adding data via the most obvious path (upload) creates a managed delta table. This means it has different data types, a different location, and there is no .csv file left. This in turn will break a lot of code later in the labs.

Uploading a file to dbfs (the less obvious option) provides the old interface with an external table, the correct data types and the correct location for the remainder of the course.

**Comment by GraemeMalcolm** [comment]
Thanks @douwevandenberg for reporting - instructions updated.
